version: "3.2"
services:
  db-server:
    image: "postgres:11.1-alpine"
    container_name: happy-family-db
    # https://pythonspeed.com/articles/faster-db-tests/
    command: postgres  -c shared_buffers=256MB -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=family
    # https://docs.docker.com/v17.09/engine/admin/volumes/tmpfs/#specify-tmpfs-options
  # application:
  #   build: "./server"
  #   container_name: happy-family-application
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db-server



